[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
dockerContext = "backend"

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
