name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        lfs: true
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: |
        cd backend
        docker build -t trimodal-xai-backend:test .
    
    - name: Run container for testing
      run: |
        docker run -d --name test-container -p 8000:8000 trimodal-xai-backend:test
        sleep 30  # Wait for startup
    
    - name: Test health endpoint
      run: |
        curl -f http://localhost:8000/health || exit 1
    
    - name: Test classes endpoint
      run: |
        curl -f http://localhost:8000/classes || exit 1
    
    - name: View container logs
      if: always()
      run: |
        docker logs test-container
    
    - name: Stop container
      if: always()
      run: |
        docker stop test-container
        docker rm test-container
